import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import test from "node:test";

import { protocolVendorContents, sameBytes, sha256 } from "../scripts/source-sync.mjs";

test("protocol vendoring produces a generated header and preserves source", () => {
  const commit = "0123456789abcdef0123456789abcdef01234567";
  const result = protocolVendorContents({
    commit,
    source: "export type Probe = { ok: true };\n",
  });

  assert.match(result, /Do not edit this file by hand/);
  assert.match(result, new RegExp(commit));
  assert.ok(result.endsWith("export type Probe = { ok: true };\n"));
});

test("byte comparison does not normalize generated artifacts", () => {
  assert.equal(sameBytes("alpha\n", Buffer.from("alpha\n")), true);
  assert.equal(sameBytes("alpha\n", Buffer.from("alpha")), false);
});

test("sha256 metadata is deterministic", () => {
  assert.equal(sha256("wmux"), "68b080606ebd3042a8cecc940155de1ac18eb77c462e61157f4460b2b4851ac6");
});
