// Generated by scripts/sync-protocol.mjs from gisenberg/wmux@56b182bfcf695a63850175ef007047db75cb5c23.
// Do not edit this file by hand.

export declare const KEYBINDING_ACTIONS: readonly [
  "commandPalette.open",
  "settings.open",
  "sidebar.toggle",
  "workspace.new",
  "workspace.close",
  "workspace.previous",
  "workspace.next",
  "workspace.select1",
  "workspace.select2",
  "workspace.select3",
  "workspace.select4",
  "workspace.select5",
  "workspace.select6",
  "workspace.select7",
  "workspace.select8",
  "workspace.select9",
  "tab.new",
  "tab.close",
  "tab.previous",
  "tab.next",
  "tab.select1",
  "tab.select2",
  "tab.select3",
  "tab.select4",
  "tab.select5",
  "tab.select6",
  "tab.select7",
  "tab.select8",
  "tab.select9",
  "pane.splitRight",
  "pane.splitDown",
  "pane.focusPrevious",
  "pane.focusNext",
  "notification.latestUnread",
  "terminal.insertNewline",
  "terminal.wordPrevious",
  "terminal.wordNext",
  "settings.save",
];
export type KeybindingAction = (typeof KEYBINDING_ACTIONS)[number];
export type KeybindingMap = Record<KeybindingAction, string[]>;
export type KeybindingOverrides = Partial<KeybindingMap>;
export type KeybindingContext = "global" | "terminal" | "settings";
export declare const isKeybindingAction: (value: string) => value is KeybindingAction;
export declare const keybindingContext: (action: KeybindingAction) => KeybindingContext;
export declare const defaultKeybindings: KeybindingMap;
export declare const resolveKeybindings: (overrides?: KeybindingOverrides) => KeybindingMap;
declare const MODIFIERS: readonly ["Primary", "Ctrl", "Alt", "Shift", "Meta"];
type KeyModifier = (typeof MODIFIERS)[number];
export interface ParsedKeyChord {
  canonical: string;
  code: string;
  modifiers: ReadonlySet<KeyModifier>;
}
export declare const parseKeyChord: (input: string) => ParsedKeyChord;
export interface KeyboardEventLike {
  code: string;
  ctrlKey: boolean;
  altKey: boolean;
  shiftKey: boolean;
  metaKey: boolean;
}
export declare const keyChordMatches: (event: KeyboardEventLike, chord: ParsedKeyChord, apple: boolean) => boolean;
export type CompiledKeybindingMap = Record<KeybindingAction, ParsedKeyChord[]>;
export declare const compileKeybindings: (bindings: KeybindingMap) => CompiledKeybindingMap;
export declare const eventMatchesAction: (
  event: KeyboardEventLike,
  bindings: CompiledKeybindingMap,
  action: KeybindingAction,
  apple: boolean,
) => boolean;
export declare const formatKeyChord: (input: string, apple: boolean) => string;
export declare const displayBindingForAction: (
  bindings: KeybindingMap,
  action: KeybindingAction,
  apple: boolean,
) => string | undefined;
export declare const validateKeybindingMap: (bindings: KeybindingMap) => string[];
export {};
