import { Buffer } from "node:buffer";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { access, readFile } from "node:fs/promises";
import path from "node:path";

export const WMUX_REPOSITORY = "https://github.com/gisenberg/wmux";
export const WMUX_RAW_ROOT = "https://raw.githubusercontent.com/gisenberg/wmux";

export const sha256 = (contents) => createHash("sha256").update(contents).digest("hex");

export const pathExists = async (candidate) => {
  try {
    await access(candidate);
    return true;
  } catch {
    return false;
  }
};

export const readPinnedCommit = async (sourceFile) => {
  const commit = (await readFile(sourceFile, "utf8")).trim();
  if (!/^[0-9a-f]{40}$/.test(commit)) {
    throw new Error(`${sourceFile} must contain one full 40-character Git commit SHA`);
  }
  return commit;
};

export const adjacentWmuxDirectory = (projectRoot) =>
  path.resolve(process.env.WMUX_SOURCE_DIR ?? path.join(projectRoot, "..", "wmux"));

export const currentCommit = (repositoryDirectory) =>
  execFileSync("git", ["-C", repositoryDirectory, "rev-parse", "HEAD"], {
    encoding: "utf8",
  }).trim();

export const readAtCommit = async ({ repositoryDirectory, commit, sourcePath }) => {
  if (await pathExists(path.join(repositoryDirectory, ".git"))) {
    try {
      return execFileSync("git", ["-C", repositoryDirectory, "show", `${commit}:${sourcePath}`]);
    } catch {
      // Fall through to the pinned public source if this checkout does not contain the commit.
    }
  }

  const response = await fetch(`${WMUX_RAW_ROOT}/${commit}/${sourcePath}`);
  if (!response.ok) {
    throw new Error(`Unable to download ${sourcePath} at ${commit}: HTTP ${response.status}`);
  }
  return Buffer.from(await response.arrayBuffer());
};

export const protocolVendorContents = ({ commit, source }) =>
  [
    `// Generated by scripts/sync-protocol.mjs from gisenberg/wmux@${commit}.`,
    "// Do not edit this file by hand.",
    "",
    source.trimEnd(),
    "",
  ].join("\n");

export const sameBytes = (left, right) => Buffer.compare(Buffer.from(left), Buffer.from(right)) === 0;
